### ISSUE TITLE
[CI] Add comprehensive test execution to pre-commit hooks

### ISSUE THREAD

**Issue by baleen37** [baleen37/dotfiles#239]
## Problem

Pre-commit hooks only run basic smoke tests, while CI runs comprehensive unit and integration tests. This leads to commits passing locally but failing in CI.

## Current State

**Pre-commit (`.pre-commit-config.yaml:65`)**:
```yaml
- id: test-smoke
  name: Test - Smoke
  entry: sh -c 'export USER=${USER:-$(whoami)} && nix run --impure .#test-smoke'
```

**CI (`.github/workflows/ci.yml:157-162`)**:
```yaml
- run: nix run --impure .#test-unit
- run: nix run --impure .#test-integration
```

## Impact

**Medium Priority** - Developers may commit code that fails CI tests.

## Proposed Solution

Add comprehensive test execution to pre-commit hooks or create a pre-push hook that mirrors CI test execution.

**Options:**
1. **Option A**: Add unit/integration tests to pre-commit (slower but catches issues early)
2. **Option B**: Move comprehensive tests to pre-push hook (faster commits, catches issues before push)
3. **Option C**: Add conditional testing based on changed files

## Implementation Details

**Option B (Recommended)**: Pre-push hook
```yaml
- id: test-comprehensive
  name: Test - Comprehensive (Unit + Integration)
  entry: sh -c 'export USER=${USER:-$(whoami)} && nix run --impure .#test-unit && nix run --impure .#test-integration'
  stages: [pre-push]
```

## Files to Modify

- `.pre-commit-config.yaml`

## Acceptance Criteria

- [ ] Pre-commit or pre-push hooks run same tests as CI
- [ ] Local test execution matches CI test execution
- [ ] Performance impact is acceptable for developer workflow

## Parent Issue

Related to #238

## Component/Module Affected

Pre-commit hooks, Testing

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>
